version: 1.2
workflows:
 - name: TheiaProk_Illumina_PE_PHB_PrimerClip
   subclass: WDL
   primaryDescriptorPath: /workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
   testParameterFiles:
    - /tests/inputs/empty.json